### ISSUE TITLE
Mover esse repo para o caecom

### ISSUE THREAD

**Issue by gab0gomes** [ruanmed/form-mat-tcc-cecomp#1]
Oi, @ruanmed. Não seria uma boa colocar esse repositório na organização também?

**Comment by ruanmed** [comment]
Opa, vou colocar sim, só tenho que limpar ele fazer os comentários de como preencher.

Posso já mover e colocar isso como "Issue", né? 

Alterarei o nome para `template-form-mat-latex-cecomp` para seguir o padrão.

**Comment by gab0gomes** [comment]
Não entendi a pergunta. :S

**Comment by ruanmed** [comment]
No caso, colocar a limpeza como um Issue nesse repositório haha.

**Comment by gab0gomes** [comment]
Ah, entendi. Show!

**Comment by ruanmed** [comment]
Resolvido, já movi para o CAECOM. 😄
